# Kotlin 예외 및 예외 처리

kotlin의 모든 예외 클래스는 최상위 예외 클래스인 `Throwable`을 상속함!

![image](https://user-images.githubusercontent.com/42997924/236492214-eead6d55-1027-4f31-ab1e-a1687ae3cd2e.png)

## 1. Error와 Exception

### 1-1. Error

- 시스템에 비정상적인 상황이 발생
- 예측이 어렵고 기본적으로 복구가 불가능 함
- JVM 시스템 자체의 오류가 대부분!

| Error Name           | 발생 원인                                                                                                   |
|----------------------|---------------------------------------------------------------------------------------------------------|
| OutOfMemoryError     | JVM이 요청한 메모리 양을 할당할 수 없을 때 발생. 주로 시스템 메모리가 부족하거나, GC(Garbage Collection)가 메모리를 더 이상 회수하지 못하는 경우에 발생 가능. |
| StackOverflowError   | 스택 메모리 영역이 부족할 때 발생. 일반적으로 재귀 호출에서 종료 조건이 제대로 설정되지 않아 무한 재귀 호출이 발생하는 경우에 주로 보임.                         |
| NoClassDefFoundError | 클래스 정의를 찾지 못했을 때 발생. 일반적으로 클래스패스에 필요한 클래스나 JAR가 없는 경우에 발생 가능.                                           |
| UnsatisfiedLinkError | JVM이 네이티브 라이브러리를 찾지 못했을 때, 또는 해당 메서드가 네이티브 코드와 매핑되지 않았을 때 발생.                                           |
| InternalError        | JVM이 자체 오류로 인해 작동하지 않는 경우 발생.                                                                           |
| UnknownError         | 알 수 없는 이유로 JVM이 작동하지 않는 경우 발생.                                                                          |

### 1-2. Exception

Java에서 Exception은 크게 UncheckedException, CheckedException으로 나뉨

#### Unchecked Exception

- 컴파일러가 예외 처리를 강제하지 않는다
- 주로 프로그램의 버그로부터 발생
- ex) NullPointerException, ArrayIndexOutOfBoundsException ...

#### CheckedException

- 컴파일러가 예외 처리를 강제한다
- 주로 외부 시스템에서 발생하는 예외 상황에 대비하기 위함
- ex) IOException, SQLException, FileNotFoundException ...

 이는 Kotlin이 "checked exceptions"라는 개념을 포함하지 않기 때문인데, 이러한 설계 결정은 예외 처리를 더 간결하고 유연하게 만드는 데 도움이 됩니다. 아래 표에 이 두 가지 종류의 예외 처리를 간략히 정리해보겠습니다:

#### Kotlin에서 Exception

- ⭐️ Kotlin에서는 Java와는 다르게 모든 예외가 `Unchecked Exception`으로 취급된다!
- 예외를 처리하도록 강제하지 않아 코드가 더 깔끔하고 간결하게 유지될 수 있다.(컴파일러가 예외 처리를 강제하지 않음)
- 개발자는 예외 처리를 필요한 곳에만 적용할 수 있다!


## 2. 예외 처리(try-catch)

- 예외가 발생할 수 있는 코드는 `try` 블록 내부에 작성한다
- `try` 블록은 하나 이상의 `catch` 블록을 가질 수 있으며, 이는 발생할 수 있는 각각의 예외 유형을 처리한다
- `finally` 블록은 항상 실행되는 코드(Optional)
- Kotlin과 Java 모두 `try-catch-finally` 구문 사용 가능하다

```kotlin
try {
  // 예외가 발생할 수 있는 코드
} catch (e: Exception) {
  // 예외 처리
} finally {
  // 항상 실행되는 코드
}
```

### 2-1. 예외 발생시키기(throw)

- `throw` 키워드를 사용하여 특정한 예외를 발생시킬 수 있다
- Kotlin과 Java 모두 `throw` 키워드 사용은 동일!

```kotlin
throw Exception("예외 발생")
```

### 2-2. Kotlin의 표현식

- ⭐️ Kotlin은 `try-catch`와 `throw`역시 표현식이다!
- 코드가 깔끔해진다

```kotlin
val result = try {
    // 예외가 발생할 수 있는 코드
    "Success"
} catch (e: Exception) {
    // 예외 처리
    "Failure"
}
```

`throw`도 표현식으로 활용하면 이렇게 사용할 수 있다.

```kotlin
fun failFast(message: String): Nothing {
    throw IllegalArgumentException(message)
}
```

```kotlin
fun main() {
    val a: String? = null
    val b: String = a ?: failFast("a is null ")
    println(b.length)
}
```

(참고) `Nothing` 타입을 반환하면 컴파일러가 해당 코드 이후는 실행되지 않는다는 경고를 보여준다!
